### ISSUE TITLE
Null reference when getting events

### ISSUE THREAD

**Issue by M-Patrone** [OfficeDev/Office365-Discovery-Service-Sample#1]
I'm not sure whether this is the right place to post this issue.
I want to access my Calendar Events by using O365 Rest Api  which causes a **Serverside** Nullreference Exception.
I have to following code:

``` C#
await outlookClient.Me.Calendar.Events.Take(20).ExecuteAsync()
```

Details of the exception:
Microsoft.OData.Client.DataServiceClientException: Error processing response stream. Server failed with following message:
Object reference not set to an instance of an object. ---> Microsoft.OData.Core.ODataErrorException: An error was read from the payload. See the 'Error' property for more details.
   at Microsoft.OData.Core.Json.BufferingJsonReader.ProcessObjectValue()
   at Microsoft.OData.Core.Json.BufferingJsonReader.ReadNextAndCheckForInStreamError()
   at Microsoft.OData.Core.Json.BufferingJsonReader.ReadInternal()
   at Microsoft.OData.Core.Json.BufferingJsonReader.Read()
   at Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadFeedContentStart()
   at Microsoft.OData.Core.JsonLight.ODataJsonLightReader.ReadFeedStart(ODataFeed feed, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.Core.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker)
   at Microsoft.OData.Core.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()
   at Microsoft.OData.Core.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.Core.ODataReaderCore.ReadSynchronously()
   at Microsoft.OData.Core.ODataReaderCore.InterceptException[T](Func`1 action)
   at Microsoft.OData.Core.ODataReaderCore.Read()
   at Microsoft.OData.Client.Materialization.ODataReaderWrapper.Read()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryRead()
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryRead()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryStartReadFeedOrEntry()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryReadFeedOrEntry(Boolean lazy, ODataFeed& feed, MaterializerEntry& entry)
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.Read()
   at Microsoft.OData.Client.Materialization.ODataReaderEntityMaterializer.ReadNextFeedOrEntry()
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__1`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.OData.ProxyExtensions.PagedCollection`2..ctor(DataServiceContextWrapper context, QueryOperationResponse`1 qor)
   at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<>c__DisplayClass38`2.<ExecuteAsync>b__36(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<ExecuteAsync>d__3a`2.MoveNext()a
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SplitViewApp2.Pages.Page3.<GetOutlookClient>d__2.MoveNext()

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
